# Generated by Django 4.2.1 on 2023-05-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='name')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='cost')),
                ('description', models.TextField(verbose_name='description')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('img_card', models.ImageField(blank=True, upload_to='', verbose_name='image')),
            ],
        ),
    ]
